layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

bio: "Adventurous, Focused, Driven, Always up for a new challenge!"

about: "PhD candidate in Software Engineering at UC Irvine, under the supervision of <a href=\"https://www.ics.uci.edu/~malek/\">Dr. Sam Malek</a>. My research focus is on Automated Software Testing and Analysis using machine learning techniques as well as data analysis. My dissertation focus is on advancing accessibility testing and repair in mobile apps.
In my heart of hearts, I am a researcher with a passion in automation and curiosity in learning from observations. "

email: f.mehralian90@gmail.com


social_media:
  linkedin: fmehralian
  scholar: Um6LsoAAAAAJ
  github: fmehralian

  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

work:
  - company: "University of California, Irvine"
    company_url: "http://seal.ics.uci.edu"
    role: "Graduate Research Assistant"
    start: "Jun 2019"
    end: "Present"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Designed and implemented novel automated accessibility testing tools in Android apps.</li>
      <li> Discovered a core problem in utilizing image captioning for labeling unlabeld icons in Android and proposed a solution for that.</li>
      <li> Designed an Deep Learning-based technique to build an oracle for energy tests.</li>
    </ul>"

  - company: "Candelis Inc."
    company_url: "https://www.candelis.com"
    role: "Software Engineer"
    start: "Jun 2021"
    end: "Sep 2022"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li>Enabled DICOM data access over web by designing and implementation of DICOMWeb standards </li>
      <li> The Store, Retrieve, and Query APIs of this server run in a new service, integrated with the 15-year-old source code of the
company. </li>
      <li> Designed and implemented a cost-efficient archive/backup mechanism utilizing various Amazon S3 storage classes. </li>
    </ul>"

  - company: "Café Bazaar"
    company_url: "https://cafebazaar.ir/about?l=en"
    role: "Software Engineer"
    start: "Jun 2018"
    end: "Aug 2018"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li>Enabled DICOM data access over web by designing and implementation of DICOMWeb standards </li>
      <li> The Store, Retrieve, and Query APIs of this server run in a new service, integrated with the 15-year-old source code of the
company. </li>
      <li> Designed and implemented a cost-efficient archive/backup mechanism utilizing various Amazon S3 storage classes. </li>
    </ul>"



publication:
  - name: "Too Much Accessibility is Harmful! Automated Detection and Analysis of Overly Accessible Elements in Mobile Apps"
    authors: "<u>Forough Mehralian*</u>, Navid Salehnamadi*, Syed Fatiul Huq, and Sam Malek"
    conference: "<strong>ASE 2022</strong>, 37th International Conference on Automated Software Engineering, October 2022"
    pdf: "https://seal.ics.uci.edu/publications/2022_ASE_Oversight.pdf"
  - name: "Groundhog: An Automated Accessibility Crawler for Mobile Apps"
    authors: "Navid Salehnamadi*, <u>Forough Mehralian*</u>, and Sam Malek"
    conference: "<strong>ASE 2022</strong>, 37th International Conference on Automated Software Engineering, October 2022"
    pdf: "https://seal.ics.uci.edu/publications/2022_ASE_Groundhog.pdf"
  - name: "Data-driven Accessibility Repair Revisited: On the Effectiveness of Generating Labels for Icons in Android Apps"
    authors: "<u>Forough Mehralian</u>, Navid Salehnamadi, and Sam Malek"
    conference: "<strong>ESEC/FSE 2021</strong>, he ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering, August 2021"
    repo: "https://github.com/fmehralian/COALA"
    html_url: "https://dl.acm.org/doi/abs/10.1145/3468264.3468604"
  - name: "Automated Construction of Energy Test Oracle for Android"
    authors: "Reyhan Jabbarvand, <u>Forough Mehralian</u>, and Sam Malek"
    conference: "<strong>ESEC/FSE 2020</strong>, he ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering, August 2020"
    repo: "https://github.com/seal-hub/ACETON"
    html_url: "https://dl.acm.org/doi/abs/10.1145/3468264.3468604"

# projects:
#   - name: SootTutorial
#     description: A step-by-step tutorial for Soot, a Java and Android static analysis framework
#     html_url: https://github.com/noidsirius/SootTutorial
#     source: github

topics:
  - name: Java
  - name: Python
  - name: Machine Learning 
  